const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('ro-RO',{maximumFractionDigits:3});
let config=JSON.parse(localStorage.getItem('aqua-config')||'{}'),token='',live=false,selected='',map,markers=[];
const now=Date.now(), sample=[['DN80-001','Vaslui · intrare sector',46.6401,27.7276,'GSM',18],['DN80-002','Bârlad · distribuție',46.2301,27.6686,'NB-IoT',8.4],['DN80-003','Huși · rezervor',46.6745,28.0597,'GSM',26]];
let meters=JSON.parse(localStorage.getItem('aqua-demo')||'null')||sample.map((x,i)=>({id:x[0],name:x[1],lat:x[2],lng:x[3],transport:x[4],baseline:1000+i*300,limit:25,readings:Array.from({length:12},(_,j)=>({timestamp:new Date(now-(11-j)*900000-(i===2?90000000:0)).toISOString(),pulses:Math.round(j*x[5]*25),battery:88-i*12}))}));
function values(m){let r=m.readings||[],a=r.at(-2),b=r.at(-1);return {index:m.baseline+(b?b.pulses*.01:0),flow:a&&b?(b.pulses-a.pulses)*.01/((Date.parse(b.timestamp)-Date.parse(a.timestamp))/3600000):null,last:b,stale:!b||Date.now()-Date.parse(b.timestamp)>86400000};}
function status(m){let v=values(m);return v.stale?'Fără citire recentă':v.flow>m.limit?'Prag debit depășit':'Citire recentă';}
function render(){let list=meters.filter(m=>(m.id+' '+m.name).toLowerCase().includes($('#search').value.toLowerCase())&&(!$('#filter').value||m.transport===$('#filter').value));$('#meters').innerHTML=list.map(m=>{let v=values(m);return `<tr data-id="${esc(m.id)}" tabindex="0" class="${selected===m.id?'selected':''}"><td><b>${esc(m.id)}</b><br><small>${esc(m.name)} · DN80</small></td><td>${esc(m.transport)}</td><td>${fmt(v.index)}</td><td>${fmt(v.flow)}</td><td>${v.last?new Date(v.last.timestamp).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'}):'—'}</td><td><span class="pill ${status(m)!=='Citire recentă'?'warn':''}">${status(m)}</span></td></tr>`;}).join('')||'<tr><td colspan="6">Niciun contor pentru filtrul ales.</td></tr>';$('#stats').innerHTML=[['Contoare DN80',meters.length],['Citiri recente',meters.filter(m=>!values(m).stale).length],['Necesită verificare',meters.filter(m=>status(m)!=='Citire recentă').length],['Volum înregistrat m³',fmt(meters.reduce((s,m)=>s+(values(m).last?.pulses||0)*.01,0))]].map(x=>`<article><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('');if(selected)detail(selected);if(map)drawMarkers(list);}
function detail(id){selected=id;let m=meters.find(x=>x.id===id);if(!m)return;let v=values(m),r=m.readings||[],flows=r.slice(1).map((b,i)=>(b.pulses-r[i].pulses)*.01/((Date.parse(b.timestamp)-Date.parse(r[i].timestamp))/3600000)),max=Math.max(1,...flows),pts=flows.map((f,i)=>`${10+i*480/Math.max(1,flows.length-1)},${110-f/max*95}`).join(' ');$('#detail').innerHTML=`<h2>${esc(m.id)}</h2><p>${esc(m.name)} · DN80 · ${esc(m.transport)}</p><p><b>${fmt(v.index)} m³</b> index total · <b>${fmt(v.flow)} m³/h</b> debit mediu</p><p>Stare: ${status(m)} · Baterie: ${v.last?.battery==null?'—':fmt(v.last.battery)+'%'}</p><p class="muted">${m.lat}, ${m.lng} · 10 L/impuls</p><svg viewBox="0 0 500 130" role="img" aria-label="Evoluția debitului mediu între citiri"><path d="M10 115H490" stroke="#cedee6"/><polyline points="${pts}" fill="none" stroke="#1289a2" stroke-width="3"/></svg><a href="https://www.google.com/maps/search/?api=1&query=${m.lat},${m.lng}" target="_blank" rel="noopener">Deschide poziția în Google Maps ↗</a><div class="scroll"><table><thead><tr><th>Ora București</th><th>Impulsuri</th><th>Index m³</th></tr></thead><tbody>${r.slice(-12).reverse().map(x=>`<tr><td>${new Date(x.timestamp).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}</td><td>${x.pulses}</td><td>${fmt(m.baseline+x.pulses*.01)}</td></tr>`).join('')}</tbody></table></div>`;if(map){map.panTo({lat:m.lat,lng:m.lng});}else if($('#map').dataset.meter!==id){$('#map').dataset.meter=id;$('#map').innerHTML=`<iframe title="Poziția contorului în Google Maps" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=${m.lat},${m.lng}&z=14&output=embed"></iframe><p class="muted">Poziția contorului selectat. Harta cu toate contoarele necesită cheia Maps JavaScript API și Map ID.</p>`;}}
$('#meters').onclick=e=>{let row=e.target.closest('[data-id]');if(row){selected=row.dataset.id;render();}};$('#meters').onkeydown=e=>{if(e.key==='Enter'){e.target.click();}};$('#search').oninput=render;$('#filter').onchange=render;
function message(s){$('#message').textContent=s;}
async function request(path,options={}){let res=await fetch(config.api.replace(/\/$/,'')+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'}});let body=await res.json();if(!res.ok)throw Error(body.error||'Eroare server');return body;}
async function refresh(){if(!live)return;try{meters=await request('/api/meters');render();$('#mode').textContent='Date server — recepție GSM / NB-IoT prin adaptorul furnizorului';message('Actualizat: '+new Date().toLocaleTimeString('ro-RO'));}catch(e){message('Citirile nu au fost actualizate: '+e.message);$('#mode').textContent='Conexiune server indisponibilă — sunt afișate ultimele date primite.';}}
$('#add').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),m=Object.fromEntries(f);['lat','lng','baseline','limit'].forEach(k=>m[k]=Number(m[k]));m.readings=[];try{if(meters.some(x=>x.id===m.id))throw Error('ID deja existent');if(live){await request('/api/meters',{method:'POST',body:JSON.stringify(m)});await refresh();}else{meters.push(m);localStorage.setItem('aqua-demo',JSON.stringify(meters));render();}e.target.reset();message('Contor salvat'+(live?' pe server.':' în demonstrația acestui browser.'));}catch(err){message(err.message);}};
$('#export').onclick=()=>{let lines=[['id','amplasament','transmisie','latitudine','longitudine','timestamp_UTC','impulsuri','index_m3','debit_mediu_m3_h']];meters.forEach(m=>(m.readings||[]).forEach((r,i,all)=>lines.push([m.id,m.name,m.transport,m.lat,m.lng,r.timestamp,r.pulses,m.baseline+r.pulses*.01,i?(r.pulses-all[i-1].pulses)*.01/((Date.parse(r.timestamp)-Date.parse(all[i-1].timestamp))/3600000):''])));let csv='\ufeff'+lines.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='aqua-nova-citiri.csv';a.click();URL.revokeObjectURL(url);};
async function loadMap(){if(!config.maps||!config.mapId)return;try{if(!window.google?.maps){await new Promise((resolve,reject)=>{window.aquaMapReady=resolve;window.gm_authFailure=()=>message('Google Maps: verifică cheia, domeniul autorizat și facturarea.');let s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key:config.maps,callback:'aquaMapReady',loading:'async',v:'weekly',libraries:'marker'});s.onerror=reject;document.head.append(s);});}map=new google.maps.Map($('#map'),{center:{lat:46.64,lng:27.73},zoom:9,mapId:config.mapId});map.addListener('click',e=>{let form=$('#add');form.elements.lat.value=e.latLng.lat().toFixed(6);form.elements.lng.value=e.latLng.lng().toFixed(6);message('Coordonate completate în formular.');});drawMarkers(meters);}catch{message('Harta Google Maps nu a putut fi încărcată.');}}
function drawMarkers(list){markers.forEach(m=>m.map=null);markers=list.map(m=>{let pin=document.createElement('button');pin.textContent=m.id;pin.style.background=status(m)==='Citire recentă'?'#08647d':'#a56612';let marker=new google.maps.marker.AdvancedMarkerElement({map,position:{lat:m.lat,lng:m.lng},title:m.id+' '+m.name,content:pin});pin.onclick=()=>{selected=m.id;render();};return marker;});}
Object.entries(config).forEach(([k,v])=>{if($('#settings').elements[k])$('#settings').elements[k].value=v;});
$('#settings').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);token=f.get('token');config={api:f.get('api').trim(),maps:f.get('maps').trim(),mapId:f.get('mapId').trim()};if(config.api&&!/^https:\/\//.test(config.api)&&!/^http:\/\/(localhost|127\.0\.0\.1)(:|\/|$)/.test(config.api)){message('Serverul trebuie să utilizeze HTTPS.');return;}localStorage.setItem('aqua-config',JSON.stringify(config));if(config.api){try{let data=await request('/api/meters');live=true;meters=data;selected='';$('#detail').innerHTML='<h2>Detalii contor</h2><p>Selectează un contor.</p>';$('#mode').textContent='Date server — recepție GSM / NB-IoT prin adaptorul furnizorului';render();message('Conectat la server.');}catch(err){message('Conectare nereușită: '+err.message);}}else message('Configurarea hărții a fost salvată.');await loadMap();};
$('#demo').onclick=()=>{live=false;config.api='';localStorage.setItem('aqua-config',JSON.stringify(config));location.reload();};
render();loadMap();setInterval(()=>{if(live)refresh();else render();},60000);
